// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhfYJd1ZAzscA32TAlYj3oh4vwWrPU-z4',
    appId: '1:382176060857:web:b49313da7beea10da04268',
    messagingSenderId: '382176060857',
    projectId: 'learn-py-app',
    authDomain: 'learn-py-app.firebaseapp.com',
    storageBucket: 'learn-py-app.appspot.com',
    measurementId: 'G-73BHQ7R308',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-dLXZ5dtkDldFtqEmhSlRu2Emh3VW5U',
    appId: '1:382176060857:android:e46431ead57be26ea04268',
    messagingSenderId: '382176060857',
    projectId: 'learn-py-app',
    storageBucket: 'learn-py-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWS8vky08Q2T2jaCpB9VbIrCBBdXSzXQ',
    appId: '1:382176060857:ios:413826bc12f18d67a04268',
    messagingSenderId: '382176060857',
    projectId: 'learn-py-app',
    storageBucket: 'learn-py-app.appspot.com',
    iosBundleId: 'com.example.learnPy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIWS8vky08Q2T2jaCpB9VbIrCBBdXSzXQ',
    appId: '1:382176060857:ios:413826bc12f18d67a04268',
    messagingSenderId: '382176060857',
    projectId: 'learn-py-app',
    storageBucket: 'learn-py-app.appspot.com',
    iosBundleId: 'com.example.learnPy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhfYJd1ZAzscA32TAlYj3oh4vwWrPU-z4',
    appId: '1:382176060857:web:d8b6a0c21ceef043a04268',
    messagingSenderId: '382176060857',
    projectId: 'learn-py-app',
    authDomain: 'learn-py-app.firebaseapp.com',
    storageBucket: 'learn-py-app.appspot.com',
    measurementId: 'G-44RHNZ8P50',
  );

}